name: Build Plugin

on:
  push:
    branches: [ main, master, season-2 ]
  pull_request:
    branches: [ main, master, season-2 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload SwapRod
        uses: actions/upload-artifact@v4
        with:
          name: SwapRod
          path: src/main/java/me/namelesss2/items/SwapRod.java
          retention-days: 30
          if-no-files-found: error